apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Zeeshan Ali
  annotations:
    github.com/user-login: Zeeshan Ali
    gitlab.com/user-login: ZeeshanM  # GitLab username
spec:
  profile:
    displayName: John Doe
    email: john.doe@example.com
  memberOf:
    - team-a